project:
  type: website
  output-dir: docs

website:
  title: "Colby Cooley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Data Viz"
        menu: 
          - freedom.qmd
          - sf_rents.qmd
          - obama_tweets.qmd
          - traffic_stops.qmd
      - text: "Simulations"
        menu: 
          - movie_genre.qmd
      - text: "Ethics"
        menu:
          - taxi.qmd
      - text: "Presentations"
        menu: 
          - presentation.qmd

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

